### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by dchandan** [DACCS-Climate/marble-tutorials#11]
Many external links in the "PAVICS Examples" notebook do not work. For example, in the screenshot below, the links to GitHub and "creating a new issue" do not work.
<img width="785" alt="Screenshot 2023-11-21 at 3 58 07 PM" src="https://github.com/DACCS-Climate/marble-tutorials/assets/5779123/8d1ec4e2-e8a5-4b98-a4a6-992bbc54815b">

However, curiously, the "PAVICS" link in the same image works, although it doesn't take one to `https://pavics.ouranos.ca/` as it should, rather it appears it is rendered under the `marbleclimate.com/tutorials.html` page:

<img width="1321" alt="Screenshot 2023-11-21 at 4 00 08 PM" src="https://github.com/DACCS-Climate/marble-tutorials/assets/5779123/1d88c66c-bcdc-4c08-88a2-1fc6ab8baa7a">

Several other links in the notebooks under "PAVICS Examples" similarly do not work.

**Comment by mishaschwartz** [comment]
We're no longer directly rendering these tutorials in this book
