### ISSUE TITLE
Personal Access Token for JupyterLab Git cannot be stored

### ISSUE THREAD

**Issue by alexandercyu** [DACCS-Climate/marble-tutorials#12]
Git in JupyterLab does not allow password authentication, only with Personal Access Token.  Currently there is no way to store the token in the image so the user doesn't have to keep pasting in their token.

**Comment by mishaschwartz** [comment]
As discussed in the meeting:

- actually storing personal credentials in a jupyterlab container is a security risk that we may not want to encourage
- we can include a section in the tutorial for github-specific suggestions that discuss 
    - how to create a personal access token (ie. link to the github documentation) https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens 
    - or other authentication options (ie. creating a public/private ssh key) https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by mishaschwartz** [comment]
This is discussed in the jupyterlab tutorials now
